//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_TaskSearch
    {
        public string TaskName { get; set; }
        public int Task_ID { get; set; }
        public System.DateTime Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string TaskStartDate { get; set; }
        public string TaskEndDate { get; set; }
        public string TaskPriority { get; set; }
        public string TaskStatus { get; set; }
        public Nullable<bool> IsTaskCompleted { get; set; }
        public string TaskTooltip { get; set; }
        public string ParentTask { get; set; }
        public string MappedProject { get; set; }
        public Nullable<int> TaskParentID { get; set; }
        public Nullable<int> TaskProjectID { get; set; }
        public string First_Name { get; set; }
        public Nullable<int> AssignedUserID { get; set; }
    }
}
